### ISSUE TITLE
Discord API

### ISSUE THREAD

**Issue by LightCap1337** [studentsky-portal-fis-vse/backend#13]
U vytváření serveru místo odkazu na baner bych ukládal jen id serveru (protože na frontendu to tak stejně dělám) nevím jestli to potom přejmenovat v API

**Comment by jirkavrba** [comment]
okay, co `guild_id`?

**Comment by LightCap1337** [comment]
jo to je asi jedno jestli server_id nebo guild_id jen aby to nebyl embed protože ukládat odkaz když stačí jen id

**Comment by jirkavrba** [comment]
Pull https://github.com/studentsky-portal-fis-vse/backend/pull/14

![](https://media.giphy.com/media/LSEWkbrnsioCOSwm9S/giphy.gif)
